/* MTI_DPI */

/*
 * Copyright 2002-2023 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DPI_HEADER
#define INCLUDED_DPI_HEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
run_counter_jtag_tests();

DPI_LINK_DECL int
sv_drive_jtag_pins(
    char tck_val,
    char tms_val,
    char tdi_val);

DPI_LINK_DECL char
sv_get_tdo();

DPI_LINK_DECL int
sv_jtag_step(
    char tms_in,
    char tdi_in,
    char is_last,
    char* tdo_out);

DPI_LINK_DECL int
sv_wait_cycles(
    int cycles);

#endif 
